-- =====================================================
-- SCRIPT: 02_sequences.sql
-- PROPOSITO: Crear todas las secuencias del proyecto
-- AUTOR: Daniel Arevalo - Alex Hernandez
-- FECHA: Junio 2025
-- =====================================================

-- Secuencias para tablas principales
CREATE SEQUENCE SEQ_VEHICLES_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REGIONS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MANUFACTURERS_ID START WITH 1 INCREMENT BY 1 NOCACHE;

-- Secuencias para tablas de catálogo
CREATE SEQUENCE SEQ_CONDITIONS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CYLINDERS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FUELS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TITLE_STATUSES_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TRANSMISSIONS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DRIVES_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SIZES_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TYPES_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAINT_COLORS_ID START WITH 1 INCREMENT BY 1 NOCACHE;

COMMIT;
