-- =====================================================
-- SCRIPT: 03_tables.sql
-- PROPOSITO: Crear todas las tablas del modelo de datos
-- AUTOR: Daniel Arevalo - Alex Hernandez
-- FECHA: Junio 2025
-- =====================================================

-- Tabla temporal para carga inicial de datos
CREATE TABLE TMP_CRAIGSLIST_VEHICLES (
   ID               NUMBER,
   URL              VARCHAR2(1000),
   REGION           VARCHAR2(100),
   REGION_URL       VARCHAR2(100),
   PRICE            NUMBER,
   YEAR_DATA        NUMBER,
   MANUFACTURER     VARCHAR2(100),
   MODEL            VARCHAR2(300),
   CONDITION        VARCHAR2(50),
   CYLINDERS        VARCHAR2(50),
   FUEL             VARCHAR2(50),
   ODOMETER         NUMBER,
   TITLE_STATUS     VARCHAR2(50),
   TRANSMISSION     VARCHAR2(50),
   VIN              VARCHAR2(50),
   DRIVE            VARCHAR2(50),
   SIZE_DATA        VARCHAR2(50),
   TYPE_DATA        VARCHAR2(50),
   PAINT_COLOR      VARCHAR2(50),
   IMAGE_URL        VARCHAR2(1000),
   DESCRIPTION_DATA CLOB,
   COUNTRY          VARCHAR2(100),
   STATE_DATA       VARCHAR2(50),
   LAT              NUMBER,
   LONGITUDE        NUMBER,
   POSTING_DATE     VARCHAR2(100)
) TABLESPACE TS_DATOS;

-- Tabla de regiones
CREATE TABLE REGIONS (
   ID         NUMBER DEFAULT SEQ_REGIONS_ID.NEXTVAL,
   REGION     VARCHAR2(100),
   REGION_URL VARCHAR2(100),
   COUNTRY    VARCHAR2(100),
   STATE_DATA VARCHAR2(50),
   LAT        NUMBER,
   LONGITUDE  NUMBER
) TABLESPACE TS_DATOS;

-- Tabla de fabricantes
CREATE TABLE MANUFACTURERS (
   ID   NUMBER DEFAULT SEQ_MANUFACTURERS_ID.NEXTVAL,
   NAME VARCHAR2(100)
) TABLESPACE TS_DATOS;

-- Tablas para atributos categóricos
CREATE TABLE CONDITIONS (
   ID   NUMBER DEFAULT SEQ_CONDITIONS_ID.NEXTVAL,
   NAME VARCHAR2(50)
) TABLESPACE TS_DATOS;

CREATE TABLE CYLINDERS (
   ID   NUMBER DEFAULT SEQ_CYLINDERS_ID.NEXTVAL,
   NAME VARCHAR2(50)
) TABLESPACE TS_DATOS;

CREATE TABLE FUELS (
   ID   NUMBER DEFAULT SEQ_FUELS_ID.NEXTVAL,
   NAME VARCHAR2(50)
) TABLESPACE TS_DATOS;

CREATE TABLE TITLE_STATUSES (
   ID   NUMBER DEFAULT SEQ_TITLE_STATUSES_ID.NEXTVAL,
   NAME VARCHAR2(50)
) TABLESPACE TS_DATOS;

CREATE TABLE TRANSMISSIONS (
   ID   NUMBER DEFAULT SEQ_TRANSMISSIONS_ID.NEXTVAL,
   NAME VARCHAR2(50)
) TABLESPACE TS_DATOS;

CREATE TABLE DRIVES (
   ID   NUMBER DEFAULT SEQ_DRIVES_ID.NEXTVAL,
   NAME VARCHAR2(50)
) TABLESPACE TS_DATOS;

CREATE TABLE SIZES (
   ID   NUMBER DEFAULT SEQ_SIZES_ID.NEXTVAL,
   NAME VARCHAR2(50)
) TABLESPACE TS_DATOS;

CREATE TABLE TYPES (
   ID   NUMBER DEFAULT SEQ_TYPES_ID.NEXTVAL,
   NAME VARCHAR2(50)
) TABLESPACE TS_DATOS;

CREATE TABLE PAINT_COLORS (
   ID   NUMBER DEFAULT SEQ_PAINT_COLORS_ID.NEXTVAL,
   NAME VARCHAR2(50)
) TABLESPACE TS_DATOS;

-- Tabla principal de vehículos
CREATE TABLE VEHICLES (
   ID               NUMBER DEFAULT SEQ_VEHICLES_ID.NEXTVAL,
   URL              VARCHAR2(1000),
   REGION_ID        NUMBER,
   PRICE            NUMBER,
   YEAR             NUMBER,
   MANUFACTURER_ID  NUMBER,
   MODEL            VARCHAR2(300),
   CONDITION_ID     NUMBER,
   CYLINDERS_ID     NUMBER,
   FUEL_ID          NUMBER,
   ODOMETER         NUMBER,
   TITLE_STATUS_ID  NUMBER,
   TRANSMISSION_ID  NUMBER,
   VIN              VARCHAR2(50),
   DRIVE_ID         NUMBER,
   SIZE_ID          NUMBER,
   TYPE_ID          NUMBER,
   PAINT_COLOR_ID   NUMBER,
   IMAGE_URL        VARCHAR2(1000),
   DESCRIPTION_DATA CLOB,
   POSTING_DATE     DATE
) TABLESPACE TS_DATOS;

COMMIT;
