-- =====================================================
-- SCRIPT: 04_constraints.sql
-- PROPOSITO: Crear todas las restricciones (PK, FK, UK, CHECK)
-- AUTOR: Daniel Arevalo - Alex Hernandez
-- FECHA: Junio 2025
-- =====================================================

-- PRIMARY KEYS
ALTER TABLE VEHICLES ADD CONSTRAINT PK_VEHICLES PRIMARY KEY (ID);
ALTER TABLE REGIONS ADD CONSTRAINT PK_REGIONS PRIMARY KEY (ID);
ALTER TABLE MANUFACTURERS ADD CONSTRAINT PK_MANUFACTURERS PRIMARY KEY (ID);
ALTER TABLE CONDITIONS ADD CONSTRAINT PK_CONDITIONS PRIMARY KEY (ID);
ALTER TABLE CYLINDERS ADD CONSTRAINT PK_CYLINDERS PRIMARY KEY (ID);
ALTER TABLE FUELS ADD CONSTRAINT PK_FUELS PRIMARY KEY (ID);
ALTER TABLE TITLE_STATUSES ADD CONSTRAINT PK_TITLE_STATUSES PRIMARY KEY (ID);
ALTER TABLE TRANSMISSIONS ADD CONSTRAINT PK_TRANSMISSIONS PRIMARY KEY (ID);
ALTER TABLE DRIVES ADD CONSTRAINT PK_DRIVES PRIMARY KEY (ID);
ALTER TABLE SIZES ADD CONSTRAINT PK_SIZES PRIMARY KEY (ID);
ALTER TABLE TYPES ADD CONSTRAINT PK_TYPES PRIMARY KEY (ID);
ALTER TABLE PAINT_COLORS ADD CONSTRAINT PK_PAINT_COLORS PRIMARY KEY (ID);

-- FOREIGN KEYS
ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_REGION FOREIGN KEY (REGION_ID)
      REFERENCES REGIONS (ID);

ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_MANUFACTURER FOREIGN KEY (MANUFACTURER_ID)
      REFERENCES MANUFACTURERS (ID);

ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_CONDITION FOREIGN KEY (CONDITION_ID)
      REFERENCES CONDITIONS (ID);

ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_CYLINDERS FOREIGN KEY (CYLINDERS_ID)
      REFERENCES CYLINDERS (ID);

ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_FUEL FOREIGN KEY (FUEL_ID)
      REFERENCES FUELS (ID);

ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_TITLE FOREIGN KEY (TITLE_STATUS_ID)
      REFERENCES TITLE_STATUSES (ID);

ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_TRANSMISSION FOREIGN KEY (TRANSMISSION_ID)
      REFERENCES TRANSMISSIONS (ID);

ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_DRIVE FOREIGN KEY (DRIVE_ID)
      REFERENCES DRIVES (ID);

ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_SIZE FOREIGN KEY (SIZE_ID)
      REFERENCES SIZES (ID);

ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_TYPE FOREIGN KEY (TYPE_ID)
      REFERENCES TYPES (ID);

ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_COLOR FOREIGN KEY (PAINT_COLOR_ID)
      REFERENCES PAINT_COLORS (ID);

-- UNIQUE CONSTRAINTS (evitar nombres repetidos en atributos categóricos)
ALTER TABLE MANUFACTURERS ADD CONSTRAINT UQ_MANUFACTURER_NAME UNIQUE (NAME);
ALTER TABLE CONDITIONS ADD CONSTRAINT UQ_CONDITION_NAME UNIQUE (NAME);
ALTER TABLE CYLINDERS ADD CONSTRAINT UQ_CYLINDERS_NAME UNIQUE (NAME);
ALTER TABLE FUELS ADD CONSTRAINT UQ_FUEL_NAME UNIQUE (NAME);
ALTER TABLE TITLE_STATUSES ADD CONSTRAINT UQ_TITLE_STATUS_NAME UNIQUE (NAME);
ALTER TABLE TRANSMISSIONS ADD CONSTRAINT UQ_TRANSMISSION_NAME UNIQUE (NAME);
ALTER TABLE DRIVES ADD CONSTRAINT UQ_DRIVE_NAME UNIQUE (NAME);
ALTER TABLE SIZES ADD CONSTRAINT UQ_SIZE_NAME UNIQUE (NAME);
ALTER TABLE TYPES ADD CONSTRAINT UQ_TYPE_NAME UNIQUE (NAME);
ALTER TABLE PAINT_COLORS ADD CONSTRAINT UQ_PAINT_COLOR_NAME UNIQUE (NAME);

-- CHECK CONSTRAINTS
ALTER TABLE VEHICLES ADD CONSTRAINT CHK_ODOMETER_POSITIVE CHECK (ODOMETER >= 0);

COMMIT;
