-- =====================================================
-- SCRIPT: 05_indexes.sql
-- PROPOSITO: Crear índices para optimizar consultas
-- AUTOR: Daniel Arevalo - Alex Hernandez
-- FECHA: Junio 2025
-- =====================================================

-- Índices para la tabla VEHICLES (consultas más frecuentes)
CREATE INDEX IDX_VEHICLES_MANUFACTURER 
   ON VEHICLES(MANUFACTURER_ID) 
   TABLESPACE TS_INDICES;

CREATE INDEX IDX_VEHICLES_YEAR 
   ON VEHICLES(YEAR) 
   TABLESPACE TS_INDICES;

CREATE INDEX IDX_VEHICLES_PRICE 
   ON VEHICLES(PRICE) 
   TABLESPACE TS_INDICES;

CREATE INDEX IDX_VEHICLES_REGION 
   ON VEHICLES(REGION_ID) 
   TABLESPACE TS_INDICES;

CREATE INDEX IDX_VEHICLES_CONDITION 
   ON VEHICLES(CONDITION_ID) 
   TABLESPACE TS_INDICES;

CREATE INDEX IDX_VEHICLES_FUEL 
   ON VEHICLES(FUEL_ID) 
   TABLESPACE TS_INDICES;

CREATE INDEX IDX_VEHICLES_TRANSMISSION 
   ON VEHICLES(TRANSMISSION_ID) 
   TABLESPACE TS_INDICES;

CREATE INDEX IDX_VEHICLES_TYPE 
   ON VEHICLES(TYPE_ID) 
   TABLESPACE TS_INDICES;

CREATE INDEX IDX_VEHICLES_POSTING_DATE 
   ON VEHICLES(POSTING_DATE) 
   TABLESPACE TS_INDICES;

-- Índice compuesto para búsquedas combinadas frecuentes
CREATE INDEX IDX_VEHICLES_SEARCH 
   ON VEHICLES(MANUFACTURER_ID, YEAR, PRICE) 
   TABLESPACE TS_INDICES;

-- Índices para tablas de catálogo (búsquedas por nombre)
CREATE INDEX IDX_MANUFACTURERS_NAME 
   ON MANUFACTURERS(NAME) 
   TABLESPACE TS_INDICES;

CREATE INDEX IDX_REGIONS_COUNTRY_STATE 
   ON REGIONS(COUNTRY, STATE_DATA) 
   TABLESPACE TS_INDICES;

COMMIT;
