CREATE TABLESPACE TS_DATOS
   DATAFILE 'ts_datos01.dbf' SIZE 300M
   AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- Tablespace para índices
CREATE TABLESPACE TS_INDICES
   DATAFILE 'ts_indices01.dbf' SIZE 50M
   AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;


-- Crear usuario
CREATE USER CARS_USER IDENTIFIED BY A123
   DEFAULT TABLESPACE TS_DATOS
   TEMPORARY TABLESPACE TEMP
   QUOTA UNLIMITED ON TS_DATOS
   QUOTA UNLIMITED ON TS_INDICES;

-- Permisos mínimos necesarios
GRANT
   CREATE SESSION
TO CARS_USER;
GRANT
   CREATE TABLE
TO CARS_USER;
GRANT
   CREATE VIEW
TO CARS_USER;
GRANT
   CREATE PROCEDURE
TO CARS_USER;
GRANT
   CREATE TRIGGER
TO CARS_USER;
GRANT
   CREATE SEQUENCE
TO CARS_USER;
GRANT
   CREATE SYNONYM
TO CARS_USER;

CREATE TABLE TMP_CRAIGSLIST_VEHICLES (
   ID               NUMBER,
   URL              VARCHAR2(1000),
   REGION           VARCHAR2(100),
   REGION_URL       VARCHAR2(100),
   PRICE            NUMBER,
   YEAR_DATA        NUMBER,
   MANUFACTURER     VARCHAR2(100),
   MODEL            VARCHAR2(300),
   CONDITION        VARCHAR2(50),
   CYLINDERS        VARCHAR2(50),
   FUEL             VARCHAR2(50),
   ODOMETER         NUMBER,
   TITLE_STATUS     VARCHAR2(50),
   TRANSMISSION     VARCHAR2(50),
   VIN              VARCHAR2(50),
   DRIVE            VARCHAR2(50),
   SIZE_DATA        VARCHAR2(50),
   TYPE_DATA        VARCHAR2(50),
   PAINT_COLOR      VARCHAR2(50),
   IMAGE_URL        VARCHAR2(1000),
   DESCRIPTION_DATA CLOB,
   COUNTRY          VARCHAR2(100),
   STATE_DATA       VARCHAR2(50),
   LAT              NUMBER,
   LONGITUDE        NUMBER,
   POSTING_DATE     VARCHAR2(100)
)
TABLESPACE TS_DATOS;

-------

CREATE SEQUENCE SEQ_VEHICLES_ID START WITH 1 INCREMENT BY 1 NOCACHE;
-- Tabla principal de vehículos
CREATE TABLE VEHICLES (
   ID               NUMBER DEFAULT SEQ_VEHICLES_ID.NEXTVAL,
   URL              VARCHAR2(1000),
   REGION_ID        NUMBER,
   PRICE            NUMBER,
   YEAR             NUMBER,
   MANUFACTURER_ID  NUMBER,
   MODEL            VARCHAR2(300),
   CONDITION_ID     NUMBER,
   CYLINDERS_ID     NUMBER,
   FUEL_ID          NUMBER,
   ODOMETER         NUMBER,
   TITLE_STATUS_ID  NUMBER,
   TRANSMISSION_ID  NUMBER,
   VIN              VARCHAR2(50),
   DRIVE_ID         NUMBER,
   SIZE_ID          NUMBER,
   TYPE_ID          NUMBER,
   PAINT_COLOR_ID   NUMBER,
   IMAGE_URL        VARCHAR2(1000),
   DESCRIPTION_DATA CLOB,
   POSTING_DATE     DATE
);

CREATE SEQUENCE SEQ_REGIONS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
-- Tabla de regiones
CREATE TABLE REGIONS (
   ID         NUMBER DEFAULT SEQ_REGIONS_ID.NEXTVAL,
   REGION     VARCHAR2(100),
   REGION_URL VARCHAR2(100),
   COUNTRY    VARCHAR2(100),
   STATE_DATA VARCHAR2(50),
   LAT        NUMBER,
   LONGITUDE  NUMBER
);

CREATE SEQUENCE SEQ_MANUFACTURERS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
-- Tabla de fabricantes
CREATE TABLE MANUFACTURERS (
   ID   NUMBER DEFAULT SEQ_MANUFACTURERS_ID.NEXTVAL,
   NAME VARCHAR2(100)
);

CREATE SEQUENCE SEQ_CONDITIONS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
-- Tablas para atributos categóricos
CREATE TABLE CONDITIONS (
   ID   NUMBER DEFAULT SEQ_CONDITIONS_ID.NEXTVAL,
   NAME VARCHAR2(50)
);

CREATE SEQUENCE SEQ_CYLINDERS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE CYLINDERS (
   ID   NUMBER DEFAULT SEQ_CYLINDERS_ID.NEXTVAL,
   NAME VARCHAR2(50)
);

CREATE SEQUENCE SEQ_FUELS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE FUELS (
   ID   NUMBER DEFAULT SEQ_FUELS_ID.NEXTVAL,
   NAME VARCHAR2(50)
);

CREATE SEQUENCE SEQ_TITLE_STATUSES_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE TITLE_STATUSES (
   ID   NUMBER DEFAULT SEQ_TITLE_STATUSES_ID.NEXTVAL,
   NAME VARCHAR2(50)
);

CREATE SEQUENCE SEQ_TRANSMISSIONS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE TRANSMISSIONS (
   ID   NUMBER DEFAULT SEQ_TRANSMISSIONS_ID.NEXTVAL,
   NAME VARCHAR2(50)
);

CREATE SEQUENCE SEQ_DRIVES_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE DRIVES (
   ID   NUMBER DEFAULT SEQ_DRIVES_ID.NEXTVAL,
   NAME VARCHAR2(50)
);

CREATE SEQUENCE SEQ_SIZES_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE SIZES (
   ID   NUMBER DEFAULT SEQ_SIZES_ID.NEXTVAL,
   NAME VARCHAR2(50)
);

CREATE SEQUENCE SEQ_TYPES_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE TYPES (
   ID   NUMBER DEFAULT SEQ_TYPES_ID.NEXTVAL,
   NAME VARCHAR2(50)
);

CREATE SEQUENCE SEQ_PAINT_COLORS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PAINT_COLORS (
   ID   NUMBER DEFAULT SEQ_PAINT_COLORS_ID.NEXTVAL,
   NAME VARCHAR2(50)
);


-- PRIMARY KEYS
ALTER TABLE VEHICLES ADD CONSTRAINT PK_VEHICLES PRIMARY KEY ( ID );
ALTER TABLE REGIONS ADD CONSTRAINT PK_REGIONS PRIMARY KEY ( ID );
ALTER TABLE MANUFACTURERS ADD CONSTRAINT PK_MANUFACTURERS PRIMARY KEY ( ID );
ALTER TABLE CONDITIONS ADD CONSTRAINT PK_CONDITIONS PRIMARY KEY ( ID );
ALTER TABLE CYLINDERS ADD CONSTRAINT PK_CYLINDERS PRIMARY KEY ( ID );
ALTER TABLE FUELS ADD CONSTRAINT PK_FUELS PRIMARY KEY ( ID );
ALTER TABLE TITLE_STATUSES ADD CONSTRAINT PK_TITLE_STATUSES PRIMARY KEY ( ID );
ALTER TABLE TRANSMISSIONS ADD CONSTRAINT PK_TRANSMISSIONS PRIMARY KEY ( ID );
ALTER TABLE DRIVES ADD CONSTRAINT PK_DRIVES PRIMARY KEY ( ID );
ALTER TABLE SIZES ADD CONSTRAINT PK_SIZES PRIMARY KEY ( ID );
ALTER TABLE TYPES ADD CONSTRAINT PK_TYPES PRIMARY KEY ( ID );
ALTER TABLE PAINT_COLORS ADD CONSTRAINT PK_PAINT_COLORS PRIMARY KEY ( ID );

-- FOREIGN KEYS
ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_REGION FOREIGN KEY ( REGION_ID )
      REFERENCES REGIONS ( ID );
ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_MANUFACTURER FOREIGN KEY ( MANUFACTURER_ID )
      REFERENCES MANUFACTURERS ( ID );
ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_CONDITION FOREIGN KEY ( CONDITION_ID )
      REFERENCES CONDITIONS ( ID );
ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_CYLINDERS FOREIGN KEY ( CYLINDERS_ID )
      REFERENCES CYLINDERS ( ID );
ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_FUEL FOREIGN KEY ( FUEL_ID )
      REFERENCES FUELS ( ID );
ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_TITLE FOREIGN KEY ( TITLE_STATUS_ID )
      REFERENCES TITLE_STATUSES ( ID );
ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_TRANSMISSION FOREIGN KEY ( TRANSMISSION_ID )
      REFERENCES TRANSMISSIONS ( ID );
ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_DRIVE FOREIGN KEY ( DRIVE_ID )
      REFERENCES DRIVES ( ID );
ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_SIZE FOREIGN KEY ( SIZE_ID )
      REFERENCES SIZES ( ID );
ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_TYPE FOREIGN KEY ( TYPE_ID )
      REFERENCES TYPES ( ID );
ALTER TABLE VEHICLES
   ADD CONSTRAINT FK_VEHICLE_COLOR FOREIGN KEY ( PAINT_COLOR_ID )
      REFERENCES PAINT_COLORS ( ID );

-- UNIQUE CONSTRAINTS (Ejemplo: evitar nombres repetidos en atributos categóricos)
ALTER TABLE MANUFACTURERS ADD CONSTRAINT UQ_MANUFACTURER_NAME UNIQUE ( NAME );
ALTER TABLE CONDITIONS ADD CONSTRAINT UQ_CONDITION_NAME UNIQUE ( NAME );
ALTER TABLE CYLINDERS ADD CONSTRAINT UQ_CYLINDERS_NAME UNIQUE ( NAME );
ALTER TABLE FUELS ADD CONSTRAINT UQ_FUEL_NAME UNIQUE ( NAME );
ALTER TABLE TITLE_STATUSES ADD CONSTRAINT UQ_TITLE_STATUS_NAME UNIQUE ( NAME );
ALTER TABLE TRANSMISSIONS ADD CONSTRAINT UQ_TRANSMISSION_NAME UNIQUE ( NAME );
ALTER TABLE DRIVES ADD CONSTRAINT UQ_DRIVE_NAME UNIQUE ( NAME );
ALTER TABLE SIZES ADD CONSTRAINT UQ_SIZE_NAME UNIQUE ( NAME );
ALTER TABLE TYPES ADD CONSTRAINT UQ_TYPE_NAME UNIQUE ( NAME );
ALTER TABLE PAINT_COLORS ADD CONSTRAINT UQ_PAINT_COLOR_NAME UNIQUE ( NAME );

-- CHECK CONSTRAINTS (Ejemplo: año válido y odómetro positivo)
-- ALTER TABLE vehicles ADD CONSTRAINT chk_year_valid CHECK (year BETWEEN 1900 AND EXTRACT(YEAR FROM SYSDATE));
ALTER TABLE VEHICLES ADD CONSTRAINT CHK_ODOMETER_POSITIVE CHECK ( ODOMETER >= 0 );


SELECT *
  FROM TMP_CRAIGSLIST_VEHICLES;
SELECT *
  FROM VEHICLES;
SELECT *
  FROM TITLE_STATUSES;
SELECT *
  FROM TRANSMISSIONS;
SELECT *
  FROM REGIONS;

SELECT *
  FROM PAINT_COLORS;

COMMIT;